// FETCH NOTIFICATION
export const FETCH_LIST_NOTIFICATION_START = "FETCH_LIST_NOTIFICATION_START";
export const FETCH_LIST_NOTIFICATION_SUCCESS = "FETCH_LIST_NOTIFICATION_SUCCESS";
export const FETCH_LIST_NOTIFICATION_ERROR = "FETCH_LIST_NOTIFICATION_ERROR";

// FETCH CONNECTION
export const FETCH_LIST_CONNECTION_START = "FETCH_LIST_CONNECTION_START";
export const FETCH_LIST_CONNECTION_SUCCESS = "FETCH_LIST_CONNECTION_SUCCESS";
export const FETCH_LIST_CONNECTION_ERROR = "FETCH_LIST_CONNECTION_ERROR";
